language: java
jdk:
 - oraclejdk8
script:
 - mvn clean compile
 - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
